# Project: DelProfils1
# Makefile created by Red Panda C++ 3.4.3279

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912" "-s" "-m64" "-ladvapi32" "-lshell32" "-luuid" "-lwbemuuid" "-lole32" "-loleaut32" "-luserenv" "-lbcrypt" "-static"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-fno-ms-extensions" "-O3" "-std=c++2a" "-pipe" "-Werror=return-type" "-Werror=vla" "-std=c++20" "-O3" "-m64" "-Wall" "-Wextra" "-Wpedantic" "-DUNICODE" "-D_UNICODE" "-DWIN32_LEAN_AND_MEAN" "-DNOMINMAX" "-D_WIN32_WINNT=0x0A00"
CFLAGS   = $(INCS) "-fno-ms-extensions" "-O3" "-pipe" "-Werror=implicit-int" "-Werror=return-type" "-Werror=vla"
NASM_FLAGS   =  "-f" "elf64"
WINDRESFLAGS = 
RES      = DelProfils1_private.res
OBJ      = src/DeferredQueueStore.o src/ProfileDelete.o src/ProfileGuard.o src/SecurityContext.o src/ProfileClassification.o src/CommandLine.o src/ExecutionLock.o src/ProfileDeleteReport.o src/WmiProfileQuery.o src/Console.o src/ProfileAge.o src/ProfileLoadProbe.o src/ProfileRoot.o src/ProfileScanner.o src/PolicyStore.o main.o src/SystemProfilePaths.o src/Wildcard.o src/ProfileReconciler.o src/ProfileDeletionPlan.o src/TextEscape.o src/ProfilePolicy.o src/DeferredQueue.o $(RES)
BIN      = DelProfils1.exe
LINKOBJ  = "src/DeferredQueueStore.o" "src/ProfileDelete.o" "src/ProfileGuard.o" "src/SecurityContext.o" "src/ProfileClassification.o" "src/CommandLine.o" "src/ExecutionLock.o" "src/ProfileDeleteReport.o" "src/WmiProfileQuery.o" "src/Console.o" "src/ProfileAge.o" "src/ProfileLoadProbe.o" "src/ProfileRoot.o" "src/ProfileScanner.o" "src/PolicyStore.o" "main.o" "src/SystemProfilePaths.o" "src/Wildcard.o" "src/ProfileReconciler.o" "src/ProfileDeletionPlan.o" "src/TextEscape.o" "src/ProfilePolicy.o" "src/DeferredQueue.o" "DelProfils1_private.res"
CLEANOBJ = "src\DeferredQueueStore.o" "src\ProfileDelete.o" "src\ProfileGuard.o" "src\SecurityContext.o" "src\ProfileClassification.o" "src\CommandLine.o" "src\ExecutionLock.o" "src\ProfileDeleteReport.o" "src\WmiProfileQuery.o" "src\Console.o" "src\ProfileAge.o" "src\ProfileLoadProbe.o" "src\ProfileRoot.o" "src\ProfileScanner.o" "src\PolicyStore.o" "main.o" "src\SystemProfilePaths.o" "src\Wildcard.o" "src\ProfileReconciler.o" "src\ProfileDeletionPlan.o" "src\TextEscape.o" "src\ProfilePolicy.o" "src\DeferredQueue.o" "DelProfils1_private.res" "DelProfils1.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

DelProfils1.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "DelProfils1.exe" $(LIBS)

src/DeferredQueueStore.o: src/DeferredQueueStore.cpp src/DeferredQueue.h src/DeferredQueueStore.h
	$(CXX) -c "src/DeferredQueueStore.cpp" -o "src/DeferredQueueStore.o" $(CXXFLAGS) 

src/ProfileDelete.o: src/ProfileDelete.cpp src/ProfileDelete.h src/ProfileRoot.h
	$(CXX) -c "src/ProfileDelete.cpp" -o "src/ProfileDelete.o" $(CXXFLAGS) 

src/ProfileGuard.o: src/ProfileGuard.cpp src/ProfileGuard.h
	$(CXX) -c "src/ProfileGuard.cpp" -o "src/ProfileGuard.o" $(CXXFLAGS) 

src/SecurityContext.o: src/SecurityContext.cpp src/SecurityContext.h
	$(CXX) -c "src/SecurityContext.cpp" -o "src/SecurityContext.o" $(CXXFLAGS) 

src/ProfileClassification.o: src/ProfileClassification.cpp src/ProfilePolicy.h src/ProfileClassification.h src/WmiProfileData.h src/ProfileInfo.h src/SystemProfilePaths.h src/ProfileGuard.h src/ProfileAge.h
	$(CXX) -c "src/ProfileClassification.cpp" -o "src/ProfileClassification.o" $(CXXFLAGS) 

src/CommandLine.o: src/CommandLine.cpp src/CommandLine.h
	$(CXX) -c "src/CommandLine.cpp" -o "src/CommandLine.o" $(CXXFLAGS) 

src/ExecutionLock.o: src/ExecutionLock.cpp src/ExecutionLock.h
	$(CXX) -c "src/ExecutionLock.cpp" -o "src/ExecutionLock.o" $(CXXFLAGS) 

src/ProfileDeleteReport.o: src/ProfileDeleteReport.cpp src/ProfileDelete.h src/TextEscape.h src/ProfileDeleteReport.h
	$(CXX) -c "src/ProfileDeleteReport.cpp" -o "src/ProfileDeleteReport.o" $(CXXFLAGS) 

src/WmiProfileQuery.o: src/WmiProfileQuery.cpp src/WmiProfileData.h src/WmiProfileQuery.h
	$(CXX) -c "src/WmiProfileQuery.cpp" -o "src/WmiProfileQuery.o" $(CXXFLAGS) 

src/Console.o: src/Console.cpp src/Console.h
	$(CXX) -c "src/Console.cpp" -o "src/Console.o" $(CXXFLAGS) 

src/ProfileAge.o: src/ProfileAge.cpp src/ProfileAge.h
	$(CXX) -c "src/ProfileAge.cpp" -o "src/ProfileAge.o" $(CXXFLAGS) 

src/ProfileLoadProbe.o: src/ProfileLoadProbe.cpp src/ProfileGuard.h src/ProfileLoadProbe.h
	$(CXX) -c "src/ProfileLoadProbe.cpp" -o "src/ProfileLoadProbe.o" $(CXXFLAGS) 

src/ProfileRoot.o: src/ProfileRoot.cpp src/ProfileRoot.h
	$(CXX) -c "src/ProfileRoot.cpp" -o "src/ProfileRoot.o" $(CXXFLAGS) 

src/ProfileScanner.o: src/ProfileScanner.cpp src/WmiProfileData.h src/ProfileScanner.h src/ProfileInfo.h src/WmiProfileQuery.h src/ProfileGuard.h src/ProfileLoadProbe.h src/ProfileAge.h src/ProfileReconciler.h src/SecurityContext.h
	$(CXX) -c "src/ProfileScanner.cpp" -o "src/ProfileScanner.o" $(CXXFLAGS) 

src/PolicyStore.o: src/PolicyStore.cpp src/ProfilePolicy.h src/PolicyStore.h
	$(CXX) -c "src/PolicyStore.cpp" -o "src/PolicyStore.o" $(CXXFLAGS) 

main.o: main.cpp src/ProfilePolicy.h src/ProfileClassification.h src/ProfileDelete.h src/DeferredQueue.h src/TextEscape.h src/WmiProfileData.h src/Wildcard.h src/ProfileScanner.h src/DeferredQueueStore.h src/ProfileInfo.h src/ExecutionLock.h src/SystemProfilePaths.h src/CommandLine.h src/PolicyStore.h src/Console.h src/ProfileDeletionPlan.h src/ProfileGuard.h src/ProfileDeleteReport.h src/ProfileAge.h
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=windows-1252

src/SystemProfilePaths.o: src/SystemProfilePaths.cpp src/SystemProfilePaths.h
	$(CXX) -c "src/SystemProfilePaths.cpp" -o "src/SystemProfilePaths.o" $(CXXFLAGS) 

src/Wildcard.o: src/Wildcard.cpp src/Wildcard.h
	$(CXX) -c "src/Wildcard.cpp" -o "src/Wildcard.o" $(CXXFLAGS) 

src/ProfileReconciler.o: src/ProfileReconciler.cpp src/WmiProfileData.h src/ProfileGuard.h src/ProfileReconciler.h
	$(CXX) -c "src/ProfileReconciler.cpp" -o "src/ProfileReconciler.o" $(CXXFLAGS) 

src/ProfileDeletionPlan.o: src/ProfileDeletionPlan.cpp src/ProfilePolicy.h src/ProfileClassification.h src/WmiProfileData.h src/ProfileInfo.h src/SystemProfilePaths.h src/ProfileDeletionPlan.h src/ProfileGuard.h src/ProfileAge.h
	$(CXX) -c "src/ProfileDeletionPlan.cpp" -o "src/ProfileDeletionPlan.o" $(CXXFLAGS) 

src/TextEscape.o: src/TextEscape.cpp src/TextEscape.h
	$(CXX) -c "src/TextEscape.cpp" -o "src/TextEscape.o" $(CXXFLAGS) 

src/ProfilePolicy.o: src/ProfilePolicy.cpp src/ProfilePolicy.h src/Wildcard.h
	$(CXX) -c "src/ProfilePolicy.cpp" -o "src/ProfilePolicy.o" $(CXXFLAGS) 

src/DeferredQueue.o: src/DeferredQueue.cpp src/DeferredQueue.h
	$(CXX) -c "src/DeferredQueue.cpp" -o "src/DeferredQueue.o" $(CXXFLAGS) 

DelProfils1_private.res: DelProfils1_private.rc 
	$(WINDRES) -i "DelProfils1_private.rc" --input-format=rc -o "DelProfils1_private.res" -O coff $(WINDRESFLAGS) 

